[package]

name = "sample"
description = "A crate for simplifying generic audio sample processing."
version = "0.1.3"
authors = ["mitchmindtree <mitchell.nordine@gmail.com>"]
readme = "README.md"
keywords = ["audio", "dsp", "bit", "depth", "sound"]
license = "MIT"
repository = "https://github.com/RustAudio/sample.git"
homepage = "https://github.com/RustAudio/sample"


